language: python
python:
  - 2.7

env:
  global:
  - secure: COVERALLS TOKEN

install:
 - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
 - make .installed.cfg

script:
 - make coverage

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#digipub"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
